### PR TITLE
Use gradle wrapper whenever it's available

### PR DESCRIPTION
**Pull request by holatuwol**

### CODE REVIEW

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Thank you, pull request merged! [See changes here.](https://github.com/liferay/liferay-osgi-watch/compare/9cf0c79~1...9cf0c79) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Hey @holatuwol, thank you for your contributions! I'm curious on how you are using this tool and if it has been of help for you so far. Also, is there anything that I can improve/fix?

Thx!

**Comment by holatuwol** [comment]
@brunobasto: Right now, I'm evaluating it for use within technical support, because the Java support gives us a reduced deployment time that should help us as we're debugging issues.

I tried using it to debug what was going wrong with [portal-workflow-kaleo-service](https://github.com/liferay/com-liferay-portal-workflow/tree/master/portal-workflow-kaleo-service), but it was running into a bundle restart problem because the jar was in osgi/portal instead of osgi/modules and so it was unable to find it for the unjar task (so the module was incomplete).

Looks like the latest fixes for 2.4.1 fix that if you are running lwatch from a built environment, but sending you another pull request for if you run it after `git clean -xdf`. https://github.com/liferay/liferay-osgi-watch/pull/4

**Comment by brunobasto** [comment]
Cool. Thx. Will take a look.

**Pull request merged**
