### PR TITLE
updating gulp sass min version because of download issues

### PR DESCRIPTION
**Pull request by croucha**

### CODE REVIEW

**Comment by croucha** [comment]
Hi, I would like to update the minimum version for this due to node-sass download issues with the older version.

Thanks!

**Comment by robersongomes** [comment]
I think you also have to add the changes on package-lock.json

**Comment by croucha** [comment]
I always thought the package.lock was something to .gitgnore and only relevant to the user's local NPM install?  I believe it's only meant to track what's installed in your local through NPM.

**Comment by jbalsas** [comment]
Hey @croucha, yes, please add the generated lock file as well.

Just FYI, we are deprecating this project in favor of a more general gradle-based approach. Can you share what's your use-case and whether you'd be able to move on to a different tool?

Thanks!

**Comment by croucha** [comment]
Hi @jbalsas , thanks for the update.  So basically I have created an OSGI module/jar using com.liferay.gradle.plugins and I was hoping to have a gulp watch for this that hot swaps any of the UI files under the src/main/resources/META-INF/resources/* directory upon change so I don't have to build and deploy the jar each time.  I'm also open to a gradle solution that watches these file changes and hot swaps them too without build and deploy...

Andre

**Comment by jbalsas** [comment]
Hey @croucha, if you're using the `com.liferay.gradle.plugins` latest version, I think you might be able to run a `watch` task directly from gradle now... is that how it should work @david-truong?

**Comment by croucha** [comment]
Word, I don't see a gradle watch task available with `com.liferay.gradle.plugins` though?  If this is so, what version?

**Comment by croucha** [comment]
@jbalsas and @david-truong anybody? Hello, hello?

**Comment by david-truong** [comment]
What version of Gradle plugins are you using?  Can you try gradlew watch -t

**Comment by croucha** [comment]
Awesome, thanks for the update @david-truong.  I tried gradlew watch -t in the command line but no success.  Not recogizned.  I believe I have to setup env variable.  I'm using: classpath group: 'com.liferay', name: 'com.liferay.gradle.plugins', version: '3.9.11'

**Comment by croucha** [comment]
Right on @david-truong!  Had to setup wrapper, get around proxy issues and update to 3.11.29 but it is working!  The command deploys jar and watches for local changes and hot swaps them!

**Pull request closed without merging**
