### PR TITLE
Pipe all logging through a helper method to standardize output to the user.

### PR DESCRIPTION
**Pull request by izaera**

### CODE REVIEW

**Comment by jbalsas** [comment]
@brunobasto, can you review this one, please?

**Comment by brunobasto** [comment]
Sure! On it!

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Thank you, pull request merged! [See changes here.](https://github.com/liferay/liferay-osgi-watch/compare/09d439a~1...09d439a) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request merged**
